### PR TITLE
Added video resume event

### PR DESCRIPTION
**Pull request by 7Ds7**
Simple trigger of a video event for the resume functionality

### CODE REVIEW

**Comment by sprice** [comment]
This looks great. Thank you! Would you mind running `npm run build` to include this change in the minified version (it will make the merge cleaner).

**Comment by 7Ds7** [comment]
done :)

**Comment by sprice** [comment]
Thanks. I'll publish a new version tonight.

**Comment by 7Ds7** [comment]
I thank you :) :+1:

**Pull request merged**
